namespace TodoApi.Models;
/// <summary>
/// Represents a single task or todo item in the system
/// </summary>
public class Todo
{
    /// <summary>
    /// Unique identifier for the todo item, generated by the database
    /// </summary>
    /// <example>101</example> 
    public int Id { get; set; }

    /// <summary>
    /// main title or name of the task.
    /// </summary>
    /// <example>Refatcor the authentication service</example>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Wether or not the task has been completed
    /// </summary>
    /// <example>false</example>
    public bool IsComplete { get; set; } = false;

    /// <summary>
    /// Optional, more detailed description of the task.
    /// </summary>
    /// <example>Update the service to use the new JWT library and add integration tests.</example>
    public string? Description { get; set; }

    /// <summary>
    /// ID of the user this task is assigned to
    /// </summary>
    /// <example>1</example>
    public int user { get; set; } = 1;
}